[NODE]

[HTTP]
port = 8080

# [HTTP.SSL]
# agreeTos = true
# email = "agoblinking@isekai.dev"
# approvedDomains = ["isekai.dev"]
# ssl_port = 443
# redirect = 80

[HTTP_STATIC]
public = "/"

[HTTP_MARKDOWN."/log"]
markdown = "../LOG.md"
template = "log.template.html"

[HTTP_MARKDOWN."/"]
markdown = "../README.md"
template = "log.template.html"
 
[HTTP_ADMIN]
