[NODE]
# [LOG]
[HTTP]
port = 8080

# [HTTP_API]
[HTTP_STATIC]
public = "/"

[HTTP_MARKDOWN."/"]
markdown = "LOG.md"
template = "log.template.html"

# [[HTTP_MD]]
# path = "/"
# file = "README.md"
# template = "default.html

